config/routes.rb
TestMg::Application.routes.draw do
  resources :books

end

app/models/book.rb
class Book < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  # GET /books
  # GET /books.xml
  def index
    @books = Book.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @books }
    end
  end

  # GET /books/1
  # GET /books/1.xml
  def show
    @book = Book.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @book }
    end
  end

  # GET /books/new
  # GET /books/new.xml
  def new
    @book = Book.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @book }
      format.js
    end
  end

  # GET /books/1/edit
  def edit
    @book = Book.find(params[:id])
    respond_to do |format|
      format.html
      format.js
    end
  end

  # POST /books
  # POST /books.xml
  def create
    @book = Book.new(params[:book])

    respond_to do |format|
      if @book.save
        format.html { redirect_to(@book, :notice => 'Book was successfully created.') }
        format.xml  { render :xml => @book, :status => :created, :location => @book }
        format.js
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @book.errors, :status => :unprocessable_entity }
        format.js  { render :action => "new" }
      end
    end
  end

  # PUT /books/1
  # PUT /books/1.xml
  def update
    @book = Book.find(params[:id])

    respond_to do |format|
      if @book.update_attributes(params[:book])
        format.html { redirect_to(@book, :notice => 'Book was successfully updated.') }
        format.xml  { head :ok }
        format.js
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @book.errors, :status => :unprocessable_entity }
        format.js { render :action => "edit" }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.xml
  def destroy
    @book = Book.find(params[:id])
    @book.destroy

    respond_to do |format|
      format.html { redirect_to(books_url) }
      format.xml  { head :ok }
      format.js
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book.html.erb
<%= content_tag_for :tr, book do %>
    <td><%= book.title %></td>
    <td><%= book.author %></td>
    <td><%= book.price %></td>
    <td><%= link_to 'Show', book %></td>
    <td><%= link_to 'Edit', edit_book_path(book), :class => 'edit_book' %></td>
    <td><%= link_to 'Delete', book, :confirm => 'Are you sure?', :method => :delete, :class => 'delete_book' %></td>
  </tr>
<% end %>

app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :author %><br />
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/books/create.js.erb
$("#books tbody").append("<%= escape_javascript(render(@book)) %>")
$("#books form").remove()

app/views/books/destroy.js.erb
$("#<%= dom_id(@book) %>").remove()

app/views/books/edit.html.erb
<h1>Editing book</h1>

<%= render 'form' %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/edit.js.erb
$("#<%= dom_id(@book) %>").addClass('being_edited')
$("#<%= dom_id(@book) %> a").contents().unwrap()
$("#books").append("<%= escape_javascript(render :partial => 'form') %>")

app/views/books/index.html.erb
<h1>Listing Books</h1>

<div id="books">
  <table class="scaffold">
    <tr>
        <th>Title</th>
        <th>Author</th>
        <th>Price</th>
        <th></th>
      <th></th>
      <th></th>
    </tr>
    <%= render @books %>
  </table>

  <%= link_to 'New Book', new_book_path, :class => 'new_book' %>

</div>

app/views/books/new.html.erb
<h1>New book</h1>

<%= render 'form' %>

<%= link_to 'Back', books_path %>

app/views/books/new.js.erb
$("#books").append("<%= escape_javascript(render :partial => 'form') %>")

app/views/books/show.html.erb
<p>
  <b>Title:</b>
  <%= @book.title %>
</p>

<p>
  <b>Author:</b>
  <%= @book.author %>
</p>

<p>
  <b>Price:</b>
  <%= @book.price %>
</p>


<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/books/update.js.erb
$("#<%= dom_id(@book) %>").replaceWith(
  "<%= escape_javascript(render(@book)) %>"
)
$("#books form").remove()

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TestMg</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>